### ISSUE TITLE
A way to port this library to js

### ISSUE THREAD

**Issue by zmitry** [hasura/kriti-lang#46]
Hi, I'm looking for a way to run it in js scope, Is there a way to port haskell to js?

**Comment by solomon-b** [comment]
We could experiment with using [GHCJS](https://github.com/ghcjs/ghcjsl), but this might end up being a rather large project. Can you explain a little bit about your use case?

**Comment by solomon-b** [comment]
I'm closing this issue due to lack interest.

**Comment by abdullah2993** [comment]
well I ported this to javascript, you can check it here: https://github.com/abdullah2993/kriti-lang
