### ISSUE TITLE
Path lookup syntax

### ISSUE THREAD

**Issue by abdullah2993** [hasura/kriti-lang#50]
What is the difference between `$body.some.path` vs `$.body.some.path`?

**Comment by solomon-b** [comment]
`$body` and `$` are both variables that are being assigned to a JSON object.

In each respective case they might something like:
```
$body = { "some": { "path": "foo"}}
```
```
$ = { "body" {"some": {"path": "foo"}}}
```

**Comment by abdullah2993** [comment]
Thanks
