### ISSUE TITLE
How to stringify an object?

### ISSUE THREAD

**Issue by zion-zadik** [hasura/kriti-lang#62]
Hi

I am trying to post an HTTP request to a rabbitMQ server using Hasura Rest transformers.
RabbitMQ HTTP API requires the body of the request to include a payload prop as a string.
In the event I define in Hasura, I try to configure the request body as follows:
`{
  "properties":{},
  "routing_key":"#.popup",
  "payload": {{$body}},
  "payload_encoding":"string"
}`

Is there a way to convert {{$body}} to a "stringified" version?

**Comment by solomon-b** [comment]
Hi. This is a bug! Luckily it is a quick fix and I just wrote a PR to correct the behavior.

**Comment by solomon-b** [comment]
Closed Via #63. This will be in the next Kriti release release which will be included in the subsequent Hasura GraphQL Engine release.
